apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: plone-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: plone-operator-role
subjects:
  - kind: ServiceAccount
    name: plone-operator
    namespace: plone-operator-system
